// Code generated by ent, DO NOT EDIT.

package group

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldName, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldCurrency, v))
}

// RecipesAPIKey applies equality check predicate on the "recipes_api_key" field. It's identical to RecipesAPIKeyEQ.
func RecipesAPIKey(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldRecipesAPIKey, v))
}

// VoiceAPIKey applies equality check predicate on the "voice_api_key" field. It's identical to VoiceAPIKeyEQ.
func VoiceAPIKey(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldVoiceAPIKey, v))
}

// HouseholdSize applies equality check predicate on the "household_size" field. It's identical to HouseholdSizeEQ.
func HouseholdSize(v int) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldHouseholdSize, v))
}

// EmergencyDays applies equality check predicate on the "emergency_days" field. It's identical to EmergencyDaysEQ.
func EmergencyDays(v int) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldEmergencyDays, v))
}

// EmergencyChecklist applies equality check predicate on the "emergency_checklist" field. It's identical to EmergencyChecklistEQ.
func EmergencyChecklist(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldEmergencyChecklist, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldName, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldCurrency, v))
}

// RecipesAPIKeyEQ applies the EQ predicate on the "recipes_api_key" field.
func RecipesAPIKeyEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldRecipesAPIKey, v))
}

// RecipesAPIKeyNEQ applies the NEQ predicate on the "recipes_api_key" field.
func RecipesAPIKeyNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldRecipesAPIKey, v))
}

// RecipesAPIKeyIn applies the In predicate on the "recipes_api_key" field.
func RecipesAPIKeyIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldRecipesAPIKey, vs...))
}

// RecipesAPIKeyNotIn applies the NotIn predicate on the "recipes_api_key" field.
func RecipesAPIKeyNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldRecipesAPIKey, vs...))
}

// RecipesAPIKeyGT applies the GT predicate on the "recipes_api_key" field.
func RecipesAPIKeyGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldRecipesAPIKey, v))
}

// RecipesAPIKeyGTE applies the GTE predicate on the "recipes_api_key" field.
func RecipesAPIKeyGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldRecipesAPIKey, v))
}

// RecipesAPIKeyLT applies the LT predicate on the "recipes_api_key" field.
func RecipesAPIKeyLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldRecipesAPIKey, v))
}

// RecipesAPIKeyLTE applies the LTE predicate on the "recipes_api_key" field.
func RecipesAPIKeyLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldRecipesAPIKey, v))
}

// RecipesAPIKeyContains applies the Contains predicate on the "recipes_api_key" field.
func RecipesAPIKeyContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldRecipesAPIKey, v))
}

// RecipesAPIKeyHasPrefix applies the HasPrefix predicate on the "recipes_api_key" field.
func RecipesAPIKeyHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldRecipesAPIKey, v))
}

// RecipesAPIKeyHasSuffix applies the HasSuffix predicate on the "recipes_api_key" field.
func RecipesAPIKeyHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldRecipesAPIKey, v))
}

// RecipesAPIKeyIsNil applies the IsNil predicate on the "recipes_api_key" field.
func RecipesAPIKeyIsNil() predicate.Group {
	return predicate.Group(sql.FieldIsNull(FieldRecipesAPIKey))
}

// RecipesAPIKeyNotNil applies the NotNil predicate on the "recipes_api_key" field.
func RecipesAPIKeyNotNil() predicate.Group {
	return predicate.Group(sql.FieldNotNull(FieldRecipesAPIKey))
}

// RecipesAPIKeyEqualFold applies the EqualFold predicate on the "recipes_api_key" field.
func RecipesAPIKeyEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldRecipesAPIKey, v))
}

// RecipesAPIKeyContainsFold applies the ContainsFold predicate on the "recipes_api_key" field.
func RecipesAPIKeyContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldRecipesAPIKey, v))
}

// VoiceAPIKeyEQ applies the EQ predicate on the "voice_api_key" field.
func VoiceAPIKeyEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldVoiceAPIKey, v))
}

// VoiceAPIKeyNEQ applies the NEQ predicate on the "voice_api_key" field.
func VoiceAPIKeyNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldVoiceAPIKey, v))
}

// VoiceAPIKeyIn applies the In predicate on the "voice_api_key" field.
func VoiceAPIKeyIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldVoiceAPIKey, vs...))
}

// VoiceAPIKeyNotIn applies the NotIn predicate on the "voice_api_key" field.
func VoiceAPIKeyNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldVoiceAPIKey, vs...))
}

// VoiceAPIKeyGT applies the GT predicate on the "voice_api_key" field.
func VoiceAPIKeyGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldVoiceAPIKey, v))
}

// VoiceAPIKeyGTE applies the GTE predicate on the "voice_api_key" field.
func VoiceAPIKeyGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldVoiceAPIKey, v))
}

// VoiceAPIKeyLT applies the LT predicate on the "voice_api_key" field.
func VoiceAPIKeyLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldVoiceAPIKey, v))
}

// VoiceAPIKeyLTE applies the LTE predicate on the "voice_api_key" field.
func VoiceAPIKeyLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldVoiceAPIKey, v))
}

// VoiceAPIKeyContains applies the Contains predicate on the "voice_api_key" field.
func VoiceAPIKeyContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldVoiceAPIKey, v))
}

// VoiceAPIKeyHasPrefix applies the HasPrefix predicate on the "voice_api_key" field.
func VoiceAPIKeyHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldVoiceAPIKey, v))
}

// VoiceAPIKeyHasSuffix applies the HasSuffix predicate on the "voice_api_key" field.
func VoiceAPIKeyHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldVoiceAPIKey, v))
}

// VoiceAPIKeyIsNil applies the IsNil predicate on the "voice_api_key" field.
func VoiceAPIKeyIsNil() predicate.Group {
	return predicate.Group(sql.FieldIsNull(FieldVoiceAPIKey))
}

// VoiceAPIKeyNotNil applies the NotNil predicate on the "voice_api_key" field.
func VoiceAPIKeyNotNil() predicate.Group {
	return predicate.Group(sql.FieldNotNull(FieldVoiceAPIKey))
}

// VoiceAPIKeyEqualFold applies the EqualFold predicate on the "voice_api_key" field.
func VoiceAPIKeyEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldVoiceAPIKey, v))
}

// VoiceAPIKeyContainsFold applies the ContainsFold predicate on the "voice_api_key" field.
func VoiceAPIKeyContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldVoiceAPIKey, v))
}

// HouseholdSizeEQ applies the EQ predicate on the "household_size" field.
func HouseholdSizeEQ(v int) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldHouseholdSize, v))
}

// HouseholdSizeNEQ applies the NEQ predicate on the "household_size" field.
func HouseholdSizeNEQ(v int) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldHouseholdSize, v))
}

// HouseholdSizeIn applies the In predicate on the "household_size" field.
func HouseholdSizeIn(vs ...int) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldHouseholdSize, vs...))
}

// HouseholdSizeNotIn applies the NotIn predicate on the "household_size" field.
func HouseholdSizeNotIn(vs ...int) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldHouseholdSize, vs...))
}

// HouseholdSizeGT applies the GT predicate on the "household_size" field.
func HouseholdSizeGT(v int) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldHouseholdSize, v))
}

// HouseholdSizeGTE applies the GTE predicate on the "household_size" field.
func HouseholdSizeGTE(v int) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldHouseholdSize, v))
}

// HouseholdSizeLT applies the LT predicate on the "household_size" field.
func HouseholdSizeLT(v int) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldHouseholdSize, v))
}

// HouseholdSizeLTE applies the LTE predicate on the "household_size" field.
func HouseholdSizeLTE(v int) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldHouseholdSize, v))
}

// HouseholdSizeIsNil applies the IsNil predicate on the "household_size" field.
func HouseholdSizeIsNil() predicate.Group {
	return predicate.Group(sql.FieldIsNull(FieldHouseholdSize))
}

// HouseholdSizeNotNil applies the NotNil predicate on the "household_size" field.
func HouseholdSizeNotNil() predicate.Group {
	return predicate.Group(sql.FieldNotNull(FieldHouseholdSize))
}

// EmergencyDaysEQ applies the EQ predicate on the "emergency_days" field.
func EmergencyDaysEQ(v int) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldEmergencyDays, v))
}

// EmergencyDaysNEQ applies the NEQ predicate on the "emergency_days" field.
func EmergencyDaysNEQ(v int) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldEmergencyDays, v))
}

// EmergencyDaysIn applies the In predicate on the "emergency_days" field.
func EmergencyDaysIn(vs ...int) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldEmergencyDays, vs...))
}

// EmergencyDaysNotIn applies the NotIn predicate on the "emergency_days" field.
func EmergencyDaysNotIn(vs ...int) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldEmergencyDays, vs...))
}

// EmergencyDaysGT applies the GT predicate on the "emergency_days" field.
func EmergencyDaysGT(v int) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldEmergencyDays, v))
}

// EmergencyDaysGTE applies the GTE predicate on the "emergency_days" field.
func EmergencyDaysGTE(v int) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldEmergencyDays, v))
}

// EmergencyDaysLT applies the LT predicate on the "emergency_days" field.
func EmergencyDaysLT(v int) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldEmergencyDays, v))
}

// EmergencyDaysLTE applies the LTE predicate on the "emergency_days" field.
func EmergencyDaysLTE(v int) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldEmergencyDays, v))
}

// EmergencyDaysIsNil applies the IsNil predicate on the "emergency_days" field.
func EmergencyDaysIsNil() predicate.Group {
	return predicate.Group(sql.FieldIsNull(FieldEmergencyDays))
}

// EmergencyDaysNotNil applies the NotNil predicate on the "emergency_days" field.
func EmergencyDaysNotNil() predicate.Group {
	return predicate.Group(sql.FieldNotNull(FieldEmergencyDays))
}

// EmergencyChecklistEQ applies the EQ predicate on the "emergency_checklist" field.
func EmergencyChecklistEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldEmergencyChecklist, v))
}

// EmergencyChecklistNEQ applies the NEQ predicate on the "emergency_checklist" field.
func EmergencyChecklistNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldEmergencyChecklist, v))
}

// EmergencyChecklistIn applies the In predicate on the "emergency_checklist" field.
func EmergencyChecklistIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldEmergencyChecklist, vs...))
}

// EmergencyChecklistNotIn applies the NotIn predicate on the "emergency_checklist" field.
func EmergencyChecklistNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldEmergencyChecklist, vs...))
}

// EmergencyChecklistGT applies the GT predicate on the "emergency_checklist" field.
func EmergencyChecklistGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldEmergencyChecklist, v))
}

// EmergencyChecklistGTE applies the GTE predicate on the "emergency_checklist" field.
func EmergencyChecklistGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldEmergencyChecklist, v))
}

// EmergencyChecklistLT applies the LT predicate on the "emergency_checklist" field.
func EmergencyChecklistLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldEmergencyChecklist, v))
}

// EmergencyChecklistLTE applies the LTE predicate on the "emergency_checklist" field.
func EmergencyChecklistLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldEmergencyChecklist, v))
}

// EmergencyChecklistContains applies the Contains predicate on the "emergency_checklist" field.
func EmergencyChecklistContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldEmergencyChecklist, v))
}

// EmergencyChecklistHasPrefix applies the HasPrefix predicate on the "emergency_checklist" field.
func EmergencyChecklistHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldEmergencyChecklist, v))
}

// EmergencyChecklistHasSuffix applies the HasSuffix predicate on the "emergency_checklist" field.
func EmergencyChecklistHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldEmergencyChecklist, v))
}

// EmergencyChecklistIsNil applies the IsNil predicate on the "emergency_checklist" field.
func EmergencyChecklistIsNil() predicate.Group {
	return predicate.Group(sql.FieldIsNull(FieldEmergencyChecklist))
}

// EmergencyChecklistNotNil applies the NotNil predicate on the "emergency_checklist" field.
func EmergencyChecklistNotNil() predicate.Group {
	return predicate.Group(sql.FieldNotNull(FieldEmergencyChecklist))
}

// EmergencyChecklistEqualFold applies the EqualFold predicate on the "emergency_checklist" field.
func EmergencyChecklistEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldEmergencyChecklist, v))
}

// EmergencyChecklistContainsFold applies the ContainsFold predicate on the "emergency_checklist" field.
func EmergencyChecklistContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldEmergencyChecklist, v))
}

// HasUsers applies the HasEdge predicate on the "users" edge.
func HasUsers() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsersTable, UsersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsersWith applies the HasEdge predicate on the "users" edge with a given conditions (other predicates).
func HasUsersWith(preds ...predicate.User) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLocations applies the HasEdge predicate on the "locations" edge.
func HasLocations() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LocationsTable, LocationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLocationsWith applies the HasEdge predicate on the "locations" edge with a given conditions (other predicates).
func HasLocationsWith(preds ...predicate.Location) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newLocationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.Item) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLabels applies the HasEdge predicate on the "labels" edge.
func HasLabels() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LabelsTable, LabelsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLabelsWith applies the HasEdge predicate on the "labels" edge with a given conditions (other predicates).
func HasLabelsWith(preds ...predicate.Label) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newLabelsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDocuments applies the HasEdge predicate on the "documents" edge.
func HasDocuments() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DocumentsTable, DocumentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDocumentsWith applies the HasEdge predicate on the "documents" edge with a given conditions (other predicates).
func HasDocumentsWith(preds ...predicate.Document) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newDocumentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInvitationTokens applies the HasEdge predicate on the "invitation_tokens" edge.
func HasInvitationTokens() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InvitationTokensTable, InvitationTokensColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvitationTokensWith applies the HasEdge predicate on the "invitation_tokens" edge with a given conditions (other predicates).
func HasInvitationTokensWith(preds ...predicate.GroupInvitationToken) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newInvitationTokensStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNotifiers applies the HasEdge predicate on the "notifiers" edge.
func HasNotifiers() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NotifiersTable, NotifiersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNotifiersWith applies the HasEdge predicate on the "notifiers" edge with a given conditions (other predicates).
func HasNotifiersWith(preds ...predicate.Notifier) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newNotifiersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Group) predicate.Group {
	return predicate.Group(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Group) predicate.Group {
	return predicate.Group(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Group) predicate.Group {
	return predicate.Group(sql.NotPredicates(p))
}
