// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/consumptionentry"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/item"
)

// ConsumptionEntryCreate is the builder for creating a ConsumptionEntry entity.
type ConsumptionEntryCreate struct {
	config
	mutation *ConsumptionEntryMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (cec *ConsumptionEntryCreate) SetCreatedAt(t time.Time) *ConsumptionEntryCreate {
	cec.mutation.SetCreatedAt(t)
	return cec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cec *ConsumptionEntryCreate) SetNillableCreatedAt(t *time.Time) *ConsumptionEntryCreate {
	if t != nil {
		cec.SetCreatedAt(*t)
	}
	return cec
}

// SetUpdatedAt sets the "updated_at" field.
func (cec *ConsumptionEntryCreate) SetUpdatedAt(t time.Time) *ConsumptionEntryCreate {
	cec.mutation.SetUpdatedAt(t)
	return cec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cec *ConsumptionEntryCreate) SetNillableUpdatedAt(t *time.Time) *ConsumptionEntryCreate {
	if t != nil {
		cec.SetUpdatedAt(*t)
	}
	return cec
}

// SetItemID sets the "item_id" field.
func (cec *ConsumptionEntryCreate) SetItemID(u uuid.UUID) *ConsumptionEntryCreate {
	cec.mutation.SetItemID(u)
	return cec
}

// SetDate sets the "date" field.
func (cec *ConsumptionEntryCreate) SetDate(t time.Time) *ConsumptionEntryCreate {
	cec.mutation.SetDate(t)
	return cec
}

// SetAmount sets the "amount" field.
func (cec *ConsumptionEntryCreate) SetAmount(i int) *ConsumptionEntryCreate {
	cec.mutation.SetAmount(i)
	return cec
}

// SetType sets the "type" field.
func (cec *ConsumptionEntryCreate) SetType(c consumptionentry.Type) *ConsumptionEntryCreate {
	cec.mutation.SetType(c)
	return cec
}

// SetNote sets the "note" field.
func (cec *ConsumptionEntryCreate) SetNote(s string) *ConsumptionEntryCreate {
	cec.mutation.SetNote(s)
	return cec
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (cec *ConsumptionEntryCreate) SetNillableNote(s *string) *ConsumptionEntryCreate {
	if s != nil {
		cec.SetNote(*s)
	}
	return cec
}

// SetID sets the "id" field.
func (cec *ConsumptionEntryCreate) SetID(u uuid.UUID) *ConsumptionEntryCreate {
	cec.mutation.SetID(u)
	return cec
}

// SetNillableID sets the "id" field if the given value is not nil.
func (cec *ConsumptionEntryCreate) SetNillableID(u *uuid.UUID) *ConsumptionEntryCreate {
	if u != nil {
		cec.SetID(*u)
	}
	return cec
}

// SetItem sets the "item" edge to the Item entity.
func (cec *ConsumptionEntryCreate) SetItem(i *Item) *ConsumptionEntryCreate {
	return cec.SetItemID(i.ID)
}

// Mutation returns the ConsumptionEntryMutation object of the builder.
func (cec *ConsumptionEntryCreate) Mutation() *ConsumptionEntryMutation {
	return cec.mutation
}

// Save creates the ConsumptionEntry in the database.
func (cec *ConsumptionEntryCreate) Save(ctx context.Context) (*ConsumptionEntry, error) {
	cec.defaults()
	return withHooks(ctx, cec.sqlSave, cec.mutation, cec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cec *ConsumptionEntryCreate) SaveX(ctx context.Context) *ConsumptionEntry {
	v, err := cec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cec *ConsumptionEntryCreate) Exec(ctx context.Context) error {
	_, err := cec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cec *ConsumptionEntryCreate) ExecX(ctx context.Context) {
	if err := cec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cec *ConsumptionEntryCreate) defaults() {
	if _, ok := cec.mutation.CreatedAt(); !ok {
		v := consumptionentry.DefaultCreatedAt()
		cec.mutation.SetCreatedAt(v)
	}
	if _, ok := cec.mutation.UpdatedAt(); !ok {
		v := consumptionentry.DefaultUpdatedAt()
		cec.mutation.SetUpdatedAt(v)
	}
	if _, ok := cec.mutation.ID(); !ok {
		v := consumptionentry.DefaultID()
		cec.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cec *ConsumptionEntryCreate) check() error {
	if _, ok := cec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ConsumptionEntry.created_at"`)}
	}
	if _, ok := cec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ConsumptionEntry.updated_at"`)}
	}
	if _, ok := cec.mutation.ItemID(); !ok {
		return &ValidationError{Name: "item_id", err: errors.New(`ent: missing required field "ConsumptionEntry.item_id"`)}
	}
	if _, ok := cec.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "ConsumptionEntry.date"`)}
	}
	if _, ok := cec.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "ConsumptionEntry.amount"`)}
	}
	if v, ok := cec.mutation.Amount(); ok {
		if err := consumptionentry.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "ConsumptionEntry.amount": %w`, err)}
		}
	}
	if _, ok := cec.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "ConsumptionEntry.type"`)}
	}
	if v, ok := cec.mutation.GetType(); ok {
		if err := consumptionentry.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ConsumptionEntry.type": %w`, err)}
		}
	}
	if v, ok := cec.mutation.Note(); ok {
		if err := consumptionentry.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "ConsumptionEntry.note": %w`, err)}
		}
	}
	if len(cec.mutation.ItemIDs()) == 0 {
		return &ValidationError{Name: "item", err: errors.New(`ent: missing required edge "ConsumptionEntry.item"`)}
	}
	return nil
}

func (cec *ConsumptionEntryCreate) sqlSave(ctx context.Context) (*ConsumptionEntry, error) {
	if err := cec.check(); err != nil {
		return nil, err
	}
	_node, _spec := cec.createSpec()
	if err := sqlgraph.CreateNode(ctx, cec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	cec.mutation.id = &_node.ID
	cec.mutation.done = true
	return _node, nil
}

func (cec *ConsumptionEntryCreate) createSpec() (*ConsumptionEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &ConsumptionEntry{config: cec.config}
		_spec = sqlgraph.NewCreateSpec(consumptionentry.Table, sqlgraph.NewFieldSpec(consumptionentry.FieldID, field.TypeUUID))
	)
	if id, ok := cec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := cec.mutation.CreatedAt(); ok {
		_spec.SetField(consumptionentry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cec.mutation.UpdatedAt(); ok {
		_spec.SetField(consumptionentry.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := cec.mutation.Date(); ok {
		_spec.SetField(consumptionentry.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := cec.mutation.Amount(); ok {
		_spec.SetField(consumptionentry.FieldAmount, field.TypeInt, value)
		_node.Amount = value
	}
	if value, ok := cec.mutation.GetType(); ok {
		_spec.SetField(consumptionentry.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := cec.mutation.Note(); ok {
		_spec.SetField(consumptionentry.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if nodes := cec.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consumptionentry.ItemTable,
			Columns: []string{consumptionentry.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ItemID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ConsumptionEntryCreateBulk is the builder for creating many ConsumptionEntry entities in bulk.
type ConsumptionEntryCreateBulk struct {
	config
	err      error
	builders []*ConsumptionEntryCreate
}

// Save creates the ConsumptionEntry entities in the database.
func (cecb *ConsumptionEntryCreateBulk) Save(ctx context.Context) ([]*ConsumptionEntry, error) {
	if cecb.err != nil {
		return nil, cecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(cecb.builders))
	nodes := make([]*ConsumptionEntry, len(cecb.builders))
	mutators := make([]Mutator, len(cecb.builders))
	for i := range cecb.builders {
		func(i int, root context.Context) {
			builder := cecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConsumptionEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cecb *ConsumptionEntryCreateBulk) SaveX(ctx context.Context) []*ConsumptionEntry {
	v, err := cecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cecb *ConsumptionEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := cecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cecb *ConsumptionEntryCreateBulk) ExecX(ctx context.Context) {
	if err := cecb.Exec(ctx); err != nil {
		panic(err)
	}
}
