// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/consumptionentry"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ConsumptionEntryDelete is the builder for deleting a ConsumptionEntry entity.
type ConsumptionEntryDelete struct {
	config
	hooks    []Hook
	mutation *ConsumptionEntryMutation
}

// Where appends a list predicates to the ConsumptionEntryDelete builder.
func (ced *ConsumptionEntryDelete) Where(ps ...predicate.ConsumptionEntry) *ConsumptionEntryDelete {
	ced.mutation.Where(ps...)
	return ced
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ced *ConsumptionEntryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ced.sqlExec, ced.mutation, ced.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ced *ConsumptionEntryDelete) ExecX(ctx context.Context) int {
	n, err := ced.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ced *ConsumptionEntryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(consumptionentry.Table, sqlgraph.NewFieldSpec(consumptionentry.FieldID, field.TypeUUID))
	if ps := ced.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ced.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ced.mutation.done = true
	return affected, err
}

// ConsumptionEntryDeleteOne is the builder for deleting a single ConsumptionEntry entity.
type ConsumptionEntryDeleteOne struct {
	ced *ConsumptionEntryDelete
}

// Where appends a list predicates to the ConsumptionEntryDelete builder.
func (cedo *ConsumptionEntryDeleteOne) Where(ps ...predicate.ConsumptionEntry) *ConsumptionEntryDeleteOne {
	cedo.ced.mutation.Where(ps...)
	return cedo
}

// Exec executes the deletion query.
func (cedo *ConsumptionEntryDeleteOne) Exec(ctx context.Context) error {
	n, err := cedo.ced.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{consumptionentry.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cedo *ConsumptionEntryDeleteOne) ExecX(ctx context.Context) {
	if err := cedo.Exec(ctx); err != nil {
		panic(err)
	}
}
