// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/consumptionentry"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/item"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ConsumptionEntryUpdate is the builder for updating ConsumptionEntry entities.
type ConsumptionEntryUpdate struct {
	config
	hooks    []Hook
	mutation *ConsumptionEntryMutation
}

// Where appends a list predicates to the ConsumptionEntryUpdate builder.
func (ceu *ConsumptionEntryUpdate) Where(ps ...predicate.ConsumptionEntry) *ConsumptionEntryUpdate {
	ceu.mutation.Where(ps...)
	return ceu
}

// SetUpdatedAt sets the "updated_at" field.
func (ceu *ConsumptionEntryUpdate) SetUpdatedAt(t time.Time) *ConsumptionEntryUpdate {
	ceu.mutation.SetUpdatedAt(t)
	return ceu
}

// SetItemID sets the "item_id" field.
func (ceu *ConsumptionEntryUpdate) SetItemID(u uuid.UUID) *ConsumptionEntryUpdate {
	ceu.mutation.SetItemID(u)
	return ceu
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (ceu *ConsumptionEntryUpdate) SetNillableItemID(u *uuid.UUID) *ConsumptionEntryUpdate {
	if u != nil {
		ceu.SetItemID(*u)
	}
	return ceu
}

// SetDate sets the "date" field.
func (ceu *ConsumptionEntryUpdate) SetDate(t time.Time) *ConsumptionEntryUpdate {
	ceu.mutation.SetDate(t)
	return ceu
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (ceu *ConsumptionEntryUpdate) SetNillableDate(t *time.Time) *ConsumptionEntryUpdate {
	if t != nil {
		ceu.SetDate(*t)
	}
	return ceu
}

// SetAmount sets the "amount" field.
func (ceu *ConsumptionEntryUpdate) SetAmount(i int) *ConsumptionEntryUpdate {
	ceu.mutation.ResetAmount()
	ceu.mutation.SetAmount(i)
	return ceu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (ceu *ConsumptionEntryUpdate) SetNillableAmount(i *int) *ConsumptionEntryUpdate {
	if i != nil {
		ceu.SetAmount(*i)
	}
	return ceu
}

// AddAmount adds i to the "amount" field.
func (ceu *ConsumptionEntryUpdate) AddAmount(i int) *ConsumptionEntryUpdate {
	ceu.mutation.AddAmount(i)
	return ceu
}

// SetType sets the "type" field.
func (ceu *ConsumptionEntryUpdate) SetType(c consumptionentry.Type) *ConsumptionEntryUpdate {
	ceu.mutation.SetType(c)
	return ceu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (ceu *ConsumptionEntryUpdate) SetNillableType(c *consumptionentry.Type) *ConsumptionEntryUpdate {
	if c != nil {
		ceu.SetType(*c)
	}
	return ceu
}

// SetNote sets the "note" field.
func (ceu *ConsumptionEntryUpdate) SetNote(s string) *ConsumptionEntryUpdate {
	ceu.mutation.SetNote(s)
	return ceu
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (ceu *ConsumptionEntryUpdate) SetNillableNote(s *string) *ConsumptionEntryUpdate {
	if s != nil {
		ceu.SetNote(*s)
	}
	return ceu
}

// ClearNote clears the value of the "note" field.
func (ceu *ConsumptionEntryUpdate) ClearNote() *ConsumptionEntryUpdate {
	ceu.mutation.ClearNote()
	return ceu
}

// SetItem sets the "item" edge to the Item entity.
func (ceu *ConsumptionEntryUpdate) SetItem(i *Item) *ConsumptionEntryUpdate {
	return ceu.SetItemID(i.ID)
}

// Mutation returns the ConsumptionEntryMutation object of the builder.
func (ceu *ConsumptionEntryUpdate) Mutation() *ConsumptionEntryMutation {
	return ceu.mutation
}

// ClearItem clears the "item" edge to the Item entity.
func (ceu *ConsumptionEntryUpdate) ClearItem() *ConsumptionEntryUpdate {
	ceu.mutation.ClearItem()
	return ceu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ceu *ConsumptionEntryUpdate) Save(ctx context.Context) (int, error) {
	ceu.defaults()
	return withHooks(ctx, ceu.sqlSave, ceu.mutation, ceu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ceu *ConsumptionEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := ceu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ceu *ConsumptionEntryUpdate) Exec(ctx context.Context) error {
	_, err := ceu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ceu *ConsumptionEntryUpdate) ExecX(ctx context.Context) {
	if err := ceu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ceu *ConsumptionEntryUpdate) defaults() {
	if _, ok := ceu.mutation.UpdatedAt(); !ok {
		v := consumptionentry.UpdateDefaultUpdatedAt()
		ceu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ceu *ConsumptionEntryUpdate) check() error {
	if v, ok := ceu.mutation.Amount(); ok {
		if err := consumptionentry.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "ConsumptionEntry.amount": %w`, err)}
		}
	}
	if v, ok := ceu.mutation.GetType(); ok {
		if err := consumptionentry.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ConsumptionEntry.type": %w`, err)}
		}
	}
	if v, ok := ceu.mutation.Note(); ok {
		if err := consumptionentry.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "ConsumptionEntry.note": %w`, err)}
		}
	}
	if ceu.mutation.ItemCleared() && len(ceu.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConsumptionEntry.item"`)
	}
	return nil
}

func (ceu *ConsumptionEntryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ceu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(consumptionentry.Table, consumptionentry.Columns, sqlgraph.NewFieldSpec(consumptionentry.FieldID, field.TypeUUID))
	if ps := ceu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ceu.mutation.UpdatedAt(); ok {
		_spec.SetField(consumptionentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ceu.mutation.Date(); ok {
		_spec.SetField(consumptionentry.FieldDate, field.TypeTime, value)
	}
	if value, ok := ceu.mutation.Amount(); ok {
		_spec.SetField(consumptionentry.FieldAmount, field.TypeInt, value)
	}
	if value, ok := ceu.mutation.AddedAmount(); ok {
		_spec.AddField(consumptionentry.FieldAmount, field.TypeInt, value)
	}
	if value, ok := ceu.mutation.GetType(); ok {
		_spec.SetField(consumptionentry.FieldType, field.TypeEnum, value)
	}
	if value, ok := ceu.mutation.Note(); ok {
		_spec.SetField(consumptionentry.FieldNote, field.TypeString, value)
	}
	if ceu.mutation.NoteCleared() {
		_spec.ClearField(consumptionentry.FieldNote, field.TypeString)
	}
	if ceu.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consumptionentry.ItemTable,
			Columns: []string{consumptionentry.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ceu.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consumptionentry.ItemTable,
			Columns: []string{consumptionentry.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ceu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{consumptionentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ceu.mutation.done = true
	return n, nil
}

// ConsumptionEntryUpdateOne is the builder for updating a single ConsumptionEntry entity.
type ConsumptionEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConsumptionEntryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (ceuo *ConsumptionEntryUpdateOne) SetUpdatedAt(t time.Time) *ConsumptionEntryUpdateOne {
	ceuo.mutation.SetUpdatedAt(t)
	return ceuo
}

// SetItemID sets the "item_id" field.
func (ceuo *ConsumptionEntryUpdateOne) SetItemID(u uuid.UUID) *ConsumptionEntryUpdateOne {
	ceuo.mutation.SetItemID(u)
	return ceuo
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (ceuo *ConsumptionEntryUpdateOne) SetNillableItemID(u *uuid.UUID) *ConsumptionEntryUpdateOne {
	if u != nil {
		ceuo.SetItemID(*u)
	}
	return ceuo
}

// SetDate sets the "date" field.
func (ceuo *ConsumptionEntryUpdateOne) SetDate(t time.Time) *ConsumptionEntryUpdateOne {
	ceuo.mutation.SetDate(t)
	return ceuo
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (ceuo *ConsumptionEntryUpdateOne) SetNillableDate(t *time.Time) *ConsumptionEntryUpdateOne {
	if t != nil {
		ceuo.SetDate(*t)
	}
	return ceuo
}

// SetAmount sets the "amount" field.
func (ceuo *ConsumptionEntryUpdateOne) SetAmount(i int) *ConsumptionEntryUpdateOne {
	ceuo.mutation.ResetAmount()
	ceuo.mutation.SetAmount(i)
	return ceuo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (ceuo *ConsumptionEntryUpdateOne) SetNillableAmount(i *int) *ConsumptionEntryUpdateOne {
	if i != nil {
		ceuo.SetAmount(*i)
	}
	return ceuo
}

// AddAmount adds i to the "amount" field.
func (ceuo *ConsumptionEntryUpdateOne) AddAmount(i int) *ConsumptionEntryUpdateOne {
	ceuo.mutation.AddAmount(i)
	return ceuo
}

// SetType sets the "type" field.
func (ceuo *ConsumptionEntryUpdateOne) SetType(c consumptionentry.Type) *ConsumptionEntryUpdateOne {
	ceuo.mutation.SetType(c)
	return ceuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (ceuo *ConsumptionEntryUpdateOne) SetNillableType(c *consumptionentry.Type) *ConsumptionEntryUpdateOne {
	if c != nil {
		ceuo.SetType(*c)
	}
	return ceuo
}

// SetNote sets the "note" field.
func (ceuo *ConsumptionEntryUpdateOne) SetNote(s string) *ConsumptionEntryUpdateOne {
	ceuo.mutation.SetNote(s)
	return ceuo
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (ceuo *ConsumptionEntryUpdateOne) SetNillableNote(s *string) *ConsumptionEntryUpdateOne {
	if s != nil {
		ceuo.SetNote(*s)
	}
	return ceuo
}

// ClearNote clears the value of the "note" field.
func (ceuo *ConsumptionEntryUpdateOne) ClearNote() *ConsumptionEntryUpdateOne {
	ceuo.mutation.ClearNote()
	return ceuo
}

// SetItem sets the "item" edge to the Item entity.
func (ceuo *ConsumptionEntryUpdateOne) SetItem(i *Item) *ConsumptionEntryUpdateOne {
	return ceuo.SetItemID(i.ID)
}

// Mutation returns the ConsumptionEntryMutation object of the builder.
func (ceuo *ConsumptionEntryUpdateOne) Mutation() *ConsumptionEntryMutation {
	return ceuo.mutation
}

// ClearItem clears the "item" edge to the Item entity.
func (ceuo *ConsumptionEntryUpdateOne) ClearItem() *ConsumptionEntryUpdateOne {
	ceuo.mutation.ClearItem()
	return ceuo
}

// Where appends a list predicates to the ConsumptionEntryUpdate builder.
func (ceuo *ConsumptionEntryUpdateOne) Where(ps ...predicate.ConsumptionEntry) *ConsumptionEntryUpdateOne {
	ceuo.mutation.Where(ps...)
	return ceuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ceuo *ConsumptionEntryUpdateOne) Select(field string, fields ...string) *ConsumptionEntryUpdateOne {
	ceuo.fields = append([]string{field}, fields...)
	return ceuo
}

// Save executes the query and returns the updated ConsumptionEntry entity.
func (ceuo *ConsumptionEntryUpdateOne) Save(ctx context.Context) (*ConsumptionEntry, error) {
	ceuo.defaults()
	return withHooks(ctx, ceuo.sqlSave, ceuo.mutation, ceuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ceuo *ConsumptionEntryUpdateOne) SaveX(ctx context.Context) *ConsumptionEntry {
	node, err := ceuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ceuo *ConsumptionEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := ceuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ceuo *ConsumptionEntryUpdateOne) ExecX(ctx context.Context) {
	if err := ceuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ceuo *ConsumptionEntryUpdateOne) defaults() {
	if _, ok := ceuo.mutation.UpdatedAt(); !ok {
		v := consumptionentry.UpdateDefaultUpdatedAt()
		ceuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ceuo *ConsumptionEntryUpdateOne) check() error {
	if v, ok := ceuo.mutation.Amount(); ok {
		if err := consumptionentry.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "ConsumptionEntry.amount": %w`, err)}
		}
	}
	if v, ok := ceuo.mutation.GetType(); ok {
		if err := consumptionentry.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ConsumptionEntry.type": %w`, err)}
		}
	}
	if v, ok := ceuo.mutation.Note(); ok {
		if err := consumptionentry.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "ConsumptionEntry.note": %w`, err)}
		}
	}
	if ceuo.mutation.ItemCleared() && len(ceuo.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConsumptionEntry.item"`)
	}
	return nil
}

func (ceuo *ConsumptionEntryUpdateOne) sqlSave(ctx context.Context) (_node *ConsumptionEntry, err error) {
	if err := ceuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(consumptionentry.Table, consumptionentry.Columns, sqlgraph.NewFieldSpec(consumptionentry.FieldID, field.TypeUUID))
	id, ok := ceuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ConsumptionEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ceuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, consumptionentry.FieldID)
		for _, f := range fields {
			if !consumptionentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != consumptionentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ceuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ceuo.mutation.UpdatedAt(); ok {
		_spec.SetField(consumptionentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ceuo.mutation.Date(); ok {
		_spec.SetField(consumptionentry.FieldDate, field.TypeTime, value)
	}
	if value, ok := ceuo.mutation.Amount(); ok {
		_spec.SetField(consumptionentry.FieldAmount, field.TypeInt, value)
	}
	if value, ok := ceuo.mutation.AddedAmount(); ok {
		_spec.AddField(consumptionentry.FieldAmount, field.TypeInt, value)
	}
	if value, ok := ceuo.mutation.GetType(); ok {
		_spec.SetField(consumptionentry.FieldType, field.TypeEnum, value)
	}
	if value, ok := ceuo.mutation.Note(); ok {
		_spec.SetField(consumptionentry.FieldNote, field.TypeString, value)
	}
	if ceuo.mutation.NoteCleared() {
		_spec.ClearField(consumptionentry.FieldNote, field.TypeString)
	}
	if ceuo.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consumptionentry.ItemTable,
			Columns: []string{consumptionentry.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ceuo.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consumptionentry.ItemTable,
			Columns: []string{consumptionentry.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ConsumptionEntry{config: ceuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ceuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{consumptionentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ceuo.mutation.done = true
	return _node, nil
}
