// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/consumptionentry"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/item"
)

// ConsumptionEntry is the model entity for the ConsumptionEntry schema.
type ConsumptionEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ItemID holds the value of the "item_id" field.
	ItemID uuid.UUID `json:"item_id,omitempty"`
	// Date holds the value of the "date" field.
	Date time.Time `json:"date,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount int `json:"amount,omitempty"`
	// Type holds the value of the "type" field.
	Type consumptionentry.Type `json:"type,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ConsumptionEntryQuery when eager-loading is set.
	Edges        ConsumptionEntryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ConsumptionEntryEdges holds the relations/edges for other nodes in the graph.
type ConsumptionEntryEdges struct {
	// Item holds the value of the item edge.
	Item *Item `json:"item,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ItemOrErr returns the Item value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConsumptionEntryEdges) ItemOrErr() (*Item, error) {
	if e.Item != nil {
		return e.Item, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: item.Label}
	}
	return nil, &NotLoadedError{edge: "item"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ConsumptionEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case consumptionentry.FieldAmount:
			values[i] = new(sql.NullInt64)
		case consumptionentry.FieldType, consumptionentry.FieldNote:
			values[i] = new(sql.NullString)
		case consumptionentry.FieldCreatedAt, consumptionentry.FieldUpdatedAt, consumptionentry.FieldDate:
			values[i] = new(sql.NullTime)
		case consumptionentry.FieldID, consumptionentry.FieldItemID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ConsumptionEntry fields.
func (ce *ConsumptionEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case consumptionentry.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ce.ID = *value
			}
		case consumptionentry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ce.CreatedAt = value.Time
			}
		case consumptionentry.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ce.UpdatedAt = value.Time
			}
		case consumptionentry.FieldItemID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field item_id", values[i])
			} else if value != nil {
				ce.ItemID = *value
			}
		case consumptionentry.FieldDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				ce.Date = value.Time
			}
		case consumptionentry.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				ce.Amount = int(value.Int64)
			}
		case consumptionentry.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				ce.Type = consumptionentry.Type(value.String)
			}
		case consumptionentry.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				ce.Note = value.String
			}
		default:
			ce.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ConsumptionEntry.
// This includes values selected through modifiers, order, etc.
func (ce *ConsumptionEntry) Value(name string) (ent.Value, error) {
	return ce.selectValues.Get(name)
}

// QueryItem queries the "item" edge of the ConsumptionEntry entity.
func (ce *ConsumptionEntry) QueryItem() *ItemQuery {
	return NewConsumptionEntryClient(ce.config).QueryItem(ce)
}

// Update returns a builder for updating this ConsumptionEntry.
// Note that you need to call ConsumptionEntry.Unwrap() before calling this method if this ConsumptionEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (ce *ConsumptionEntry) Update() *ConsumptionEntryUpdateOne {
	return NewConsumptionEntryClient(ce.config).UpdateOne(ce)
}

// Unwrap unwraps the ConsumptionEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ce *ConsumptionEntry) Unwrap() *ConsumptionEntry {
	_tx, ok := ce.config.driver.(*txDriver)
	if !ok {
		panic("ent: ConsumptionEntry is not a transactional entity")
	}
	ce.config.driver = _tx.drv
	return ce
}

// String implements the fmt.Stringer.
func (ce *ConsumptionEntry) String() string {
	var builder strings.Builder
	builder.WriteString("ConsumptionEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ce.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ce.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ce.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("item_id=")
	builder.WriteString(fmt.Sprintf("%v", ce.ItemID))
	builder.WriteString(", ")
	builder.WriteString("date=")
	builder.WriteString(ce.Date.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", ce.Amount))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", ce.Type))
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(ce.Note)
	builder.WriteByte(')')
	return builder.String()
}

// ConsumptionEntries is a parsable slice of ConsumptionEntry.
type ConsumptionEntries []*ConsumptionEntry
